export const ANCHOR_TYPE = {
    TOP_CENTER: 0,
    TOP_LEFT: 1,
    TOP_RIGHT: 2,
    BOTTOM_CENTER: 3,
    BOTTOM_LEFT: 4,
    BOTTOM_RIGHT: 5,
    CENTER: 6,
    LEFT: 7,
    RIGHT: 8,
    _COUNT: 9
};

export const ANCHOR_TABLE_X = new Float16Array(ANCHOR_TYPE._COUNT);

ANCHOR_TABLE_X[ANCHOR_TYPE.TOP_CENTER] = 0.5;
ANCHOR_TABLE_X[ANCHOR_TYPE.TOP_RIGHT] = 1;
ANCHOR_TABLE_X[ANCHOR_TYPE.BOTTOM_CENTER] = 0.5;
ANCHOR_TABLE_X[ANCHOR_TYPE.BOTTOM_RIGHT] = 1;
ANCHOR_TABLE_X[ANCHOR_TYPE.CENTER] = 0.5;
ANCHOR_TABLE_X[ANCHOR_TYPE.RIGHT] = 1;

export const ANCHOR_TABLE_Y = new Float16Array(ANCHOR_TYPE._COUNT);

ANCHOR_TABLE_Y[ANCHOR_TYPE.BOTTOM_LEFT] = 1;
ANCHOR_TABLE_Y[ANCHOR_TYPE.BOTTOM_CENTER] = 1;
ANCHOR_TABLE_Y[ANCHOR_TYPE.BOTTOM_RIGHT] = 1;
ANCHOR_TABLE_Y[ANCHOR_TYPE.LEFT] = 0.5;
ANCHOR_TABLE_Y[ANCHOR_TYPE.CENTER] = 0.5;
ANCHOR_TABLE_Y[ANCHOR_TYPE.RIGHT] = 0.5;