export const PLAYER_PREFERENCE = {
    FORCE_HEALTH_DRAW: 1,
    DISABLE_IDLE_ANIMATIONS: 0 //TODO: Implement!
};

export const TRAIT_CONFIG = {
    CEMENTED_STEEL_ARMOR_REDUCTION: 20,
    SHRAPNEL_RANGE: 1,
    SHRAPNEL_DAMAGE: 0.5,
    BULLDOZE_DAMAGE: 2,
    ANNIHILATE_DAMAGE: 2,
    ABSORBER_RATE: 0.2,
    OVERHEAT_DAMAGE: 0.1,
    HEROIC_THRESHOLD: 1,
    JUDGEMENT_RANGE: 3,
    DISPERSION_RANGE: 1,
    STEER_REDUCTION: 0.1,
    STEER_MAX_REDUCTION: 0.5,
    BLITZ_MULTIPLIER: 1.2,
    SCHWERPUNKT_MULTIPLIER: 1.4,
    STEALTH_MULTIPLIER: 2,
    EXECUTIONER_THRESHOLD: 0.5,
    EXECUTIONER_DAMAGE: 1.5,
    JUDGEMENT_DAMAGE: 10000,
    STREAMLINED_REDUCTION: 0.5
};

export const TEAM_STAT = {
    UNITS_BUILT: 0,
    UNITS_KILLED: 1,
    UNITS_LOST: 2,
    STRUCTURES_CAPTURED: 3,
    STRUCTURES_LOST: 4,
    RESOURCES_COLLECTED: 5,
    FINAL_SCORE: 6,
    TIME_TAKEN: 7, //deltaTime/frame. Not needed.
    ROUNDS_TAKEN: 8,
    SEA_UNITS_BUILT: 9,
    AIR_UNITS_BUILT: 10,
    GROUND_UNITS_BUILT: 11,
    ORE_EXTRACTED: 12,
    RESOURCES_SPENT: 13,
    ROUNDS_TAKEN: 14,
    UNITS_MOVED: 15,
    RESOURCE_DAMAGE: 16,
    MINES_DISCOVERED: 17,
    _COUNT: 18
};

export const JAMMER_FLAG = {
    NONE: 0,
    RADAR: 1 << 0,
    SONAR: 1 << 1,
    AIRSPACE_BLOCKED: 1 << 2
};

export const MINE_TYPE = {
    LAND: 0,
    SEA: 1
};

export const ENTITY_CATEGORY = {
    LAND: 0,
    SEA: 1,
    AIR: 2,
    _COUNT: 3
};

export const SHOP_TYPE = {
    NONE: "NONE",
    ENGINEER: "ENGINEER",
    WARMACHINE: "WARMACHINE",
    FACTORY: "FACTORY"
};

export const GAME_EVENT = {
    MP_CLIENT_SELECT_MAP: 8,
    MP_CLIENT_START_MATCH: 9,
    MP_CLIENT_ACTION_INTENT: 10,
    MP_CLIENT_MAP_LOADED: 11,
    MP_SERVER_LOAD_MAP: 12,
    MP_SERVER_LOAD_MAP_CUSTOM: 13,
    MP_SERVER_START_MAP: 14,
    MP_SERVER_STATE_UPDATE: 15
};

export const COLOR_TYPE = {
    WHITE: "WHITE"
};

export const TILE_TYPE = {
    _INVALID: -1,
    NONE: 0,
    GRASS: 1,
    BOREAL: 2,
    ARCTIC: 3,
    SHORE: 4,
    ISLAND: 5,
    SWIRL: 6,
    ROCKS: 7,
    SEA: 8,
    RIVER: 9,
    ROAD: 10,
    BRIDGE: 11,
    VOLCANO: 12,
    RICH_ORE: 13,
    USED_ORE: 14,
    DEPLETED_ORE: 15,
    CANYON: 16,
    PATH: 17,
    RAIL: 18,
    _COUNT: 19
};

export const TRAIT_TYPE = {
    STREAMLINED: "STREAMLINED",
    COUNTER_BATTERY: "COUNTER_BATTERY",
    STUN: "STUN",
    IRREPARABLE: "IRREPARABLE",
    EXECUTIONER: "EXECUTIONER",
    TANK_POOPER: "TANK_POOPER",
    SPAWNER: "SPAWNER",
    EXTRACTOR: "EXTRACTOR",
    CAPTURABLE: "CAPTURABLE",
    CONQUEROR: "CONQUEROR",
    HIGH_ALTITUDE: "HIGH_ALTITUDE",
    RADAR: "RADAR",
    UNFAIR: "UNFAIR",
    BULLDOZE: "BULLDOZE",
    ANNIHILATE: "ANNIHILATE",
    LYNCHPIN: "LYNCHPIN",
    BLITZ: "BLITZ",
    SHRAPNEL: "SHRAPNEL",
    CLEAR_SHOT: "CLEAR_SHOT",
    ARMOR_PIERCE: "ARMOR_PIERCE",
    OVERHEAT: "OVERHEAT",
    TRACKING: "TRACKING",
    BLIND_SPOT: "BLIND_SPOT",
    HEROIC: "HEROIC",
    SLUGGER: "SLUGGER",
    ELUSIVE: "ELUSIVE",
    JAMMER: "JAMMER",
    FIXED: "FIXED",
    INDOMITABLE: "INDOMITABLE",
    COMMANDO: "COMMANDO",
    ANTI_INFANTRY: "ANTI_INFANTRY",
    ANTI_AIR: "ANTI_AIR",
    ANTI_SHIP: "ANTI_SHIP",
    ANTI_TANK: "ANTI_TANK",
    ANTI_STRUCTURE: "ANTI_STRUCTURE",
    STEER: "STEER",
    STEALTH: "STEALTH",
    SCHWERPUNKT: "SCHWERPUNKT",
    CEMENTED_STEEL_ARMOR: "CEMENTED_STEEL_ARMOR",
    SUPPLY_DISTRIBUTION: "SUPPLY_DISTRIBUTION",
    CAVITATION_EXPLOSION: "CAVITATION_EXPLOSION",
    SONAR: "SONAR",
    SUBMERGED: "SUBMERGED",
    TANK_HUNTER: "TANK_HUNTER",
    SELF_DESTRUCT: "SELF_DESTRUCT",
    SKYSWEEPER: "SKYSWEEPER",
    DEPTH_CHARGE: "DEPTH_CHARGE",
    SEABOUND: "SEABOUND",
    TERRIFYING: "TERRIFYING",
    INFLAMING: "INFLAMING",
    ABSORBER: "ABSORBER",
    DISPERSION: "DISPERSION",
    JUDGEMENT: "JUDGEMENT",
    BEWEGUNGSKRIEG: "BEWEGUNGSKRIEG",
    STREAMBLAST: "STREAMBLAST",
    AIR_TRANSPORT: "AIR_TRANSPORT",
    NAVAL_TRANSPORT: "NAVAL_TRANSPORT"
};

export const MOVEMENT_TYPE = {
    STATIONARY: 0,
    FOOT: 1,
    WHEELED: 2,
    TRACKED: 3,
    RAIL: 4,
    FLIGHT: 5,
    RUDDER: 6,
    HEAVY_RUDDER: 7,
    AMPHIBIOUS: 8,
    _COUNT: 9
};

export const WEAPON_TYPE = {
    NONE: "NONE",
    LIGHT: "LIGHT",
    MEDIUM: "MEDIUM",
    HEAVY: "HEAVY"
};

export const ARMOR_TYPE = {
    NONE: 0,
    LIGHT: 1,
    MEDIUM: 2,
    HEAVY: 3,
    OMEGA: 4,
    _COUNT: 5
};

export const TERRAIN_TYPE = {
    EXTRACTABLE: "EXTRACTABLE",
    SHIELDED: "SHIELDED",
    UNEVEN: "UNEVEN",
    RUGGED: "RUGGED",
    PRECIPITOUS: "PRECIPITOUS",
    IMPASSABLE: "IMPASSABLE",
    TRICKY_WATERS: "TRICKY_WATERS",
    CONCEALMENT: "CONCEALMENT",
    NAVAL_CONCEALMENT: "NAVAL_CONCEALMENT",
    BUNKER: "BUNKER",
    SHALLOW: "SHALLOW",
    VANTAGE: "VANTAGE",
    DANGEROUS: "DANGEROUS"
};

export const CLIMATE_TYPE = {
    NONE: "NONE",
    TEMPERATE: "TEMPERATE",
    ARID: "ARID",
    BOREAL: "BOREAL",
    BARREN: "BARREN",
    ARCTIC: "ARCTIC",
    LUNAR: "LUNAR",
    MARTIAN: "MARTIAN",
    HELLISH: "HELLISH"
};

export const SCHEMA_TYPE = {
    RED: "RED",
    BLUE: "BLUE",
    GREEN: "GREEN",
    YELLOW: "YELLOW",
    DARK_RED: "DARK_RED",
    DARK_BLUE: "DARK_BLUE",
    BRONZE: "BRONZE",
    DARK_GREEN: "DARK_GREEN",
    GOLD: "GOLD",
    CYAN: "CYAN",
    PINK: "PINK",
    WHITE: "WHITE",
    PURPLE: "PURPLE",
    BLACK: "BLACK",
    GRAY: "GRAY",
    CREAM: "CREAM",
    LIME: "LIME"
};

export const POWER_TYPE = {
    MAJOR: "MAJOR",
    MINOR: "MINOR",
    REGIONAL: "REGIONAL"
};

export const NATION_TYPE = {
    SOMERTIN: "SOMERTIN",
    KARGIT: "KARGIT",
    TRANSKAL: "TRANSKAL",
    POLASIE: "POLASIE",
    ELAM: "ELAM"
};

export const CURRENCY_TYPE = {
    NONE: "NONE",
    ZLOT: "ZLOT",
    KARGIL: "KARGIL",
    KRONE: "KRONE",
    PULA: "PULA",
    RIAL: "RIAL"
};

export const FACTION_TYPE = {
    CONTINENTAL_SECURITY_LEAGUE: "CONTINENTAL_SECURITY_LEAGUE",
    GLORIOUS_COALLITION: "GLORIOUS_COALLITION",
    RED: "RED",
    BLUE: "BLUE",
    GREEN: "GREEN",
    YELLOW: "YELLOW",
    DARK_RED: "DARK_RED",
    DARK_BLUE: "DARK_BLUE",
    BRONZE: "BRONZE",
    DARK_GREEN: "DARK_GREEN",
    GOLD: "GOLD",
    CYAN: "CYAN",
    PINK: "PINK",
    WHITE: "WHITE",
    PURPLE: "PURPLE",
    BLACK: "BLACK",
    GRAY: "GRAY",
    CREAM: "CREAM",
    LIME: "LIME",
    WHITE: "WHITE"
};

export const COMMANDER_TYPE = {
    KANYE: "KANYE"
};

export const BUILDING_TYPE = {
    AIR_CONTROL: "AIR_CONTROL",
    COMMAND_CENTER: "COMMAND_CENTER",
    FACTORY: "FACTORY",
    GROUND_CONTROL: "GROUND_CONTROL",
    OIL_ADVANCED_REFINERY: "OIL_ADVANCED_REFINERY",
    OIL_REFINERY: "OIL_REFINERY",
    OIL_RIG: "OIL_RIG",
    SEA_CONTROL: "SEA_CONTROL"
};

export const ENTITY_TYPE = {
    LEVIATHAN_BARGE: "leviathan_barge",
    PELICAN_TRANSPORT: "pelican_transport",
    STORK_TRANSPORT: "stork_transport"
};

export const ACTION_TYPE = {
    MINE_TRIGGER: "MINE_TRIGGER",
    PURCHASE_ENTITY: "PURCHASE_ENTITY",
    PRODUCE_ENTITY: "PRODUCE_ENTITY",
    EXTRACT: "EXTRACT",
    ENTITY_SPAWN: "ENTITY_SPAWN",
    EXPLODE_TILE: "EXPLODE_TILE",
    CAPTURE: "CAPTURE",
    HEAL: "HEAL",
    END_TURN: "END_TURN",
    START_TURN: "START_TURN",
    MOVE: "MOVE",
    ATTACK: "ATTACK",
    CLOAK: "CLOAK",
    DEATH: "DEATH",
    UNCLOAK: "UNCLOAK"
};

export const MORALE_TYPE = {
    NONE: "NONE"
};

export const OBJECTIVE_TYPE = {
    DEFEAT: "DEFEAT",
    PROTECT: "PROTECT",
    CAPTURE: "CAPTURE",
    DEFEND: "DEFEND",
    SURVIVE: "SURVIVE",
    TIME_LIMIT: "TIME_LIMIT"
};

export const COMMAND_TYPE = {
    ATTACK: 0,
    COUNTER: 1,
};

export const EFFECT_TYPE = {
    GFX: "GFX",
    SFX: "SFX",
    EXPLOSION: "EXPLOSION"
};

export const COMPONENT_TYPE = {
    PLAY_EFFECT: "PLAY_EFFECT",
    DIALOGUE: "DIALOGUE",
    EXPLODE_TILE: "EXPLODE_TILE",
    SPAWN_ENTITY: "SPAWN_ENTITY"
};

export const AUTOTILER_TYPE = {
    PATH: "battalion_path"
};

export const LAYER_TYPE = {
    BUILDING: 0,
    SEA: 1,
    LAND: 2,
    GFX: 3,
    _COUNT: 4
};

export const TILE_ID = {
    NONE: 0,
    GRASS: 1,
    BOREAL: 2,
    ARCTIC: 3,

    ROAD_0: 4,
    ROAD_1: 5,
    ROAD_2: 6,
    ROAD_3: 7,
    ROAD_4: 8,
    ROAD_5: 9,
    ROAD_6: 10,
    ROAD_7: 11,
    ROAD_8: 12,
    ROAD_9: 13,
    ROAD_10: 14,
    ROAD_11: 15,
    ROAD_12: 16,
    ROAD_13: 17,
    ROAD_14: 18,
    ROAD_15: 19,

    VOLANO: 20,

    RIVER_0: 21,
    //21-68: RIVER
    RIVER_47: 68,

    SHORE_0: 69,
    SHORE_1: 70,
    SHORE_2: 71,
    SHORE_3: 72,
    SHORE_4: 73,
    SHORE_5: 74,
    SHORE_6: 75,
    SHORE_7: 76,
    SHORE_8: 77,
    SHORE_9: 78,
    SHORE_10: 79,
    SHORE_11: 80,

    ISLAND_1: 81,
    ISLAND_2: 82,
    ISLAND_3: 83,
    ISLAND_4: 84,
    SWIRL_1: 85,
    SWIRL_2: 86,
    SWIRL_3: 87,
    SWIRL_4: 88,
    ROCKS_1: 89,
    ROCKS_2: 90,
    ROCKS_3: 91,
    ROCKS_4: 92,

    OVERLAY_MOVE: 93,
    OVERLAY_MOVE_ATTACK: 94,
    OVERLAY_ATTACK_LIGHT: 95,
    OVERLAY_ATTACK: 96,

    PATH_0: 97,
    PATH_UP: 101,
    PATH_RIGHT: 102,
    PATH_DOWN: 103,
    PATH_LEFT: 104,
    PATH_CENTER: 105,
    PATH_15: 112,

    JAMMER: 113,

    ORE_LEFT: 114,
    ORE_RIGHT: 115,
    ORE_LEFT_USED: 116,
    ORE_RIGHT_USED: 117,
    ORE_LEFT_DEPLETED: 118,
    ORE_RIGHT_DEPLETED: 119,
    
    CANYON_0: 120,
    CANYON_47: 167,

    RAIL_0: 168,
    RAIL_15: 183,

    _COUNT: 184
};

export const DIRECTION = {
    NORTH: 1 << 0,
    EAST: 1 << 1,
    SOUTH: 1 << 2,
    WEST: 1 << 3
};

export const RANGE_TYPE = {
    NONE: 0,
    MELEE: 1,
    RANGE: 2,
    HYBRID: 3
};

export const ATTACK_FLAG = {
    NONE: 0,
    COUNTER: 1 << 0,
    SHRAPNEL: 1 << 1,
    AREA: 1 << 2,
    STREAMBLAST: 1 << 3
};

export const PATH_FLAG = {
    NONE: 0,
    UNREACHABLE: 1 << 0,
    START: 1 << 1
};

export const PATH_INTERCEPT = {
    NONE: 0,
    VALID: 1,
    ILLEGAL: 2,
    MINE: 3
};

export const ATTACK_TYPE = {
    REGULAR: 0,
    STREAMBLAST: 1,
    DISPERSION: 2,
    SUPPLY: 3
};

export const TRANSPORT_TYPE = {
    BARGE: 0,
    PELICAN: 1,
    STORK: 2
};