export const PLAYER_PREFERENCE = {
    FORCE_HEALTH_DRAW: 1,
    DISABLE_IDLE_ANIMATIONS: 0 //TODO: Implement!
};

export const EFFECT_SPRITE = {
    _INVALID: -1,
    DEATH: 0,
    FIRE: 1,
    HEAL: 2,
    _COUNT: 3
};

export const ENTITY_SPRITE = {
    _INVALID: -1,
    IDLE_UP: 0,
    IDLE_RIGHT: 1,
    IDLE_DOWN: 2,
    IDLE_LEFT: 3,
    MOVE_UP: 4,
    MOVE_RIGHT: 5,
    MOVE_DOWN: 6,
    MOVE_LEFT: 7,
    FIRE_UP: 8,
    FIRE_RIGHT: 9,
    FIRE_DOWN: 10,
    FIRE_LEFT: 11,
    _COUNT: 12
};

export const SOUND_TYPE = {
    HEAL: "heal",
    MOVE: "move",
    FIRE: "fire",
    CLOAK: "cloak",
    DEATH: "death",
    RECRUIT: "recruit",
    UNCLOAK: "uncloak",
    _COUNT: 7
};

export const INTERRUPT_TYPE = {
    NONE: 0,
    START_GAME: 1,
    END_GAME: 2,
    EVENT: 3,
    CUSTOM: 4
};

export const LOADER_RULE = {
    NONE: 0,
    ALLOW_SPECTATOR: 1 << 0,
    FIXED_ALLIES: 1 << 1,
    LOAD_OBJECTIVES: 1 << 2,
    CUSTOM_COLOR: 1 << 3,
    CREATE_EVENT_SIMULATION: 1 << 4,
    CREATE_EVENT_EFFECTS: 1 << 5
};

export const TRAIT_CONFIG = {
    COMMANDO_LOGISTIC_REDUCTION: 0.5,
    REPAIR_VALUE: 5,
    CEMENTED_STEEL_ARMOR_REDUCTION: 20,
    SHRAPNEL_RANGE: 1,
    SHRAPNEL_DAMAGE: 0.5,
    BULLDOZE_DAMAGE: 2,
    ANNIHILATE_DAMAGE: 2,
    ABSORBER_RATE: 0.2,
    OVERHEAT_DAMAGE: 0.1,
    HEROIC_THRESHOLD: 1,
    JUDGEMENT_RANGE: 3,
    DISPERSION_RANGE: 1,
    STEER_REDUCTION: 0.1,
    STEER_MAX_REDUCTION: 0.5,
    BLITZ_MULTIPLIER: 1.2,
    SCHWERPUNKT_MULTIPLIER: 1.4,
    STEALTH_MULTIPLIER: 2,
    EXECUTIONER_THRESHOLD: 0.5,
    EXECUTIONER_DAMAGE: 1.5,
    JUDGEMENT_DAMAGE: 10000,
    STREAMLINED_REDUCTION: 0.5
};

export const GAME_EVENT = {
    MP_CLIENT_SELECT_MAP: 8,
    MP_CLIENT_START_MATCH: 9,
    MP_CLIENT_ACTION_INTENT: 10,
    MP_CLIENT_MAP_LOADED: 11,
    MP_SERVER_LOAD_MAP: 12,
    MP_SERVER_START_MAP: 13,
    MP_SERVER_UPDATE: 14
};

export const TEAM_STAT = {
    UNITS_BUILT: 0,
    UNITS_KILLED: 1,
    UNITS_LOST: 2,
    STRUCTURES_CAPTURED: 3,
    STRUCTURES_LOST: 4,
    RESOURCES_COLLECTED: 5,
    FINAL_SCORE: 6,
    TIME_TAKEN: 7, //deltaTime/frame. Not needed.
    ROUNDS_TAKEN: 8,
    SEA_UNITS_BUILT: 9,
    AIR_UNITS_BUILT: 10,
    GROUND_UNITS_BUILT: 11,
    ORE_EXTRACTED: 12,
    RESOURCES_SPENT: 13,
    ROUNDS_TAKEN: 14,
    UNITS_MOVED: 15,
    RESOURCE_DAMAGE: 16,
    MINES_DISCOVERED: 17,
    _COUNT: 18
};

export const EMBLEM_TYPE = {
    SOMERTIN: 0,
    SOMERTIN_NO: 1,
    KARGIT: 2,
    KARGIT_NO: 3,
    TRANSKAL: 4,
    TRANSKAL_NO: 5,
    POLASIE: 6,
    POLASIE_NO: 7,
    ELAM: 8,
    ELAM_NO: 9
};

export const PORTRAIT_TYPE = {
    NONE: 0,
    KANYE: 1,
    _COUNT: 2
};

export const ICON_TYPE = {
    NONE: 0,

    ARMOR_LIGHT: 1,
    ARMOR_MEDIUM: 2,
    ARMOR_HEAVY: 3,

    WEAPON_LIGHT: 5,
    WEAPON_MEDIUM: 6,
    WEAPON_HEAVY: 7,
    WEAPON_NONE: 8,

    BUILDING_FINANCIAL_CENTER: 10,
    BUILDING_FISCAL_CENTER: 11,
    BUILDING_FIDUCIARY_CENTER: 12,
    BUILDING_CAPTURABLE: 13,
    BUILDING_SPAWNER: 14,
    BUILDING_AIR_PROFICIENCY: 15,
    BUILDING_LAND_PROFICIENCY: 16,
    BUILDING_SEA_PROFICIENCY: 17,

    MOVE_STATIONARY: 20,
    MOVE_FOOT: 21,
    MOVE_WHEELED: 22,
    MOVE_TRACKED: 23,
    MOVE_FLIGHT: 24,
    MOVE_RUDDER: 25,
    MOVE_HEAVY_RUDDER: 26,
    MOVE_AMPHIBIOUS: 27,
    MOVE_RAIL: 28,

    CLIMATE_TEMPERATE: 40,
    CLIMATE_ARCTIC: 41,
    CLIMATE_ARID: 42,
    CLIMATE_BARREN: 43,
    CLIMATE_BOREAL: 44,
    CLIMATE_LUNAR: 45,
    CLIMATE_MARTIAN: 46,

    BUNKER: 60,
    CONCEALMENT: 61,
    IMPASSABLE: 62,
    NAVAL_CONCEALMENT: 63,
    PRECIPITOUS: 64,
    GARRISON: 65,
    RAIL_TRANSPORT: 66, //Informs about rail transport.
    RUGGED: 67,
    SHALLOW: 68,
    TRICKY_WATERS: 69,
    UNEVEN: 70,
    TERRAIN_VANTAGE: 71,
    TERRAIN_SHIELDED: 72,
    TERRAIN_COVER: 73,
    TERRAIN_HAZARD: 74,
    TERRAIN_EXTRACTABLE: 75,

    LYNCHPIN: 80,
    MEOW: 81,
    ABSORBER: 82,
    TRAIT_BLIND_SPOT: 83,
    AIR_TRANSPORT: 84,
    ARMOR_UP: 85, //???
    ANTI: 86,
    ANTI_AIR: 87,
    ANTI_INFANTRY: 88,
    ANTI_SHIP: 89,
    ANTI_STRUCTURE: 90,
    ANTI_TANK: 91,
    BLITZ: 92,
    TRAIT_COUNTER_BATTERY: 93, //Shared with BEWEGUNGSKRIEG
    BEWEGUNGSKRIEG: 93,
    BROADSIDE: 94,
    CAVITATION_EXPLOSION: 95,
    CEMENTED_STEEL_ARMOR: 96,
    COMMANDO: 97,
    CONQUEROR: 98,
    COURAGE: 99,

    TRAIT_REPAIR: 100,
    TRAIT_IRREPARABLE: 101,
    DEPTH_CHARGE: 102,
    TRAIT_JUDGEMENT: 103,
    DEVASTATING: 104,
    DISPERSION: 105,
    STUN: 106, //TODO(neyn): Add COUNTER_BATTERY icon!
    EAGLE: 107,
    ENGINEER: 108,
    EXTRACTOR: 109,
    TRAIT_JAMMER: 110,
    TRAIT_RADAR: 111,
    HEROIC: 112,
    INDOMITABLE: 113,
    FIXED: 114,
    //115 is free!
    MARINES: 116,
    NAVAL_TRANSPORT: 117,
    TRAIT_ANNIHILATE_BULLDOZE: 118,
    SEABOUND: 119,

    REINFORCED_ARMOR: 120, //???
    SCHWERPUNKT: 121,
    SELF_DESTRUCT: 122,
    ARMOR_PIERCE: 123,
    SKYSWEEPER: 124,
    SONAR: 125,
    STEALTH: 126,
    STEER: 127,
    STREAMBLAST: 128,
    STREAMLINED: 129,
    SUBMERGED: 130,
    SUPPLY_DISTRIBUTION: 131,
    TANK_POOPER: 132,
    TANK_HUNTER: 133,
    TERRIFYING: 134,
    VANGUARD: 135, //???
    EXECUTIONER: 136,
    TRAIT_TRACKING: 137,
    TRAIT_NOT_SELECTABLE: 138
};

export const JAMMER_FLAG = {
    NONE: 0,
    RADAR: 1 << 0,
    SONAR: 1 << 1,
    AIRSPACE_BLOCKED: 1 << 2
};

export const MINE_TYPE = {
    _INVALID: -1,
    LAND: 0,
    SEA: 1,
    _COUNT: 2
};

export const MINE_CATEGORY = {
    _INVALID: -1,
    LAND: 0,
    SEA: 1,
    _COUNT: 2
};

export const ENTITY_CATEGORY = {
    LAND: 0,
    SEA: 1,
    AIR: 2,
    _COUNT: 3
};

export const SHOP_TYPE = {
    NONE: 0,
    ENGINEER: 1,
    WARMACHINE: 2,
    FACTORY: 3,
    _COUNT: 4
};

export const TILE_TYPE = {
    _INVALID: -1,
    NONE: 0,
    GRASS: 1,
    BOREAL: 2,
    ARCTIC: 3,
    SHORE: 4,
    ISLAND: 5,
    SWIRL: 6,
    ROCKS: 7,
    SEA: 8,
    RIVER: 9,
    ROAD: 10,
    BRIDGE: 11,
    VOLCANO: 12,
    RICH_ORE: 13,
    USED_ORE: 14,
    DEPLETED_ORE: 15,
    CANYON: 16,
    PATH: 17,
    RAIL: 18,
    WASTELAND: 19,
    FOREST: 20,
    HILL: 21,
    MOUNTAIN: 22,
    _COUNT: 23
};

export const TRAIT_TYPE = {
    _INVALID: -1,
    STREAMLINED: 0,
    COUNTER_BATTERY: 1,
    STUN: 2,
    IRREPARABLE: 3,
    EXECUTIONER: 4,
    TANK_POOPER: 5,
    SPAWNER: 6,
    EXTRACTOR: 7,
    CAPTURABLE: 8,
    CONQUEROR: 9,
    HIGH_ALTITUDE: 10,
    RADAR: 11,
    UNFAIR: 12,
    BULLDOZE: 13,
    ANNIHILATE: 14,
    LYNCHPIN: 15,
    BLITZ: 16,
    SHRAPNEL: 17,
    CLEAR_SHOT: 18,
    ARMOR_PIERCE: 19,
    OVERHEAT: 20,
    TRACKING: 21,
    BLIND_SPOT: 22,
    HEROIC: 23,
    SLUGGER: 24,
    ELUSIVE: 25,
    JAMMER: 26,
    FIXED: 27,
    INDOMITABLE: 28,
    COMMANDO: 29,
    ANTI_INFANTRY: 30,
    ANTI_AIR: 31,
    ANTI_SHIP: 32,
    ANTI_TANK: 33,
    ANTI_STRUCTURE: 34,
    STEER: 35,
    STEALTH: 36,
    SCHWERPUNKT: 37,
    CEMENTED_STEEL_ARMOR: 38,
    SUPPLY_DISTRIBUTION: 39,
    CAVITATION_EXPLOSION: 40,
    SONAR: 41,
    SUBMERGED: 42,
    TANK_HUNTER: 43,
    SELF_DESTRUCT: 44,
    SKYSWEEPER: 45,
    DEPTH_CHARGE: 46,
    SEABOUND: 47,
    TERRIFYING: 48,
    INFLAMING: 49,
    ABSORBER: 50,
    DISPERSION: 51,
    JUDGEMENT: 52,
    BEWEGUNGSKRIEG: 53,
    STREAMBLAST: 54,
    AIR_TRANSPORT: 55,
    NAVAL_TRANSPORT: 56,
    FINANCIAL_CENTER: 57,
    FISCAL_CENTER: 58,
    FIDUCIARY_CENTER: 59,
    CRAB: 60,
    UNBUILT: 61,
    ENGINEER: 62,
    REPAIR: 63,
    NOT_SELECTABLE: 64,
    _COUNT: 65
};

export const MOVEMENT_TYPE = {
    STATIONARY: 0,
    FOOT: 1,
    WHEELED: 2,
    TRACKED: 3,
    RAIL: 4,
    FLIGHT: 5,
    RUDDER: 6,
    HEAVY_RUDDER: 7,
    AMPHIBIOUS: 8,
    _COUNT: 9
};

export const WEAPON_TYPE = {
    NONE: 0,
    LIGHT: 1,
    MEDIUM: 2,
    HEAVY: 3,
    _COUNT: 4
};

export const ARMOR_TYPE = {
    NONE: 0,
    LIGHT: 1,
    MEDIUM: 2,
    HEAVY: 3,
    OMEGA: 4,
    _COUNT: 5
};

export const TERRAIN_TYPE = {
    EXTRACTABLE: 0,
    SHIELDED: 1,
    UNEVEN: 2,
    RUGGED: 3,
    PRECIPITOUS: 4,
    IMPASSABLE: 5,
    TRICKY_WATERS: 6,
    COVER: 7,
    CAMOUFLAGE: 8,
    NAVAL_CAMOUFLAGE: 9,
    BUNKER: 10,
    SHALLOW: 11,
    VANTAGE: 12,
    DANGEROUS: 13,
    GARRISON: 14,
    _COUNT: 15
};

export const CLIMATE_TYPE = {
    NONE: 0,
    TEMPERATE: 1,
    ARID: 2,
    BOREAL: 3,
    BARREN: 4,
    ARCTIC: 5,
    LUNAR: 6,
    MARTIAN: 7,
    HELLISH: 8,
    _COUNT: 9
};

export const SCHEMA_TYPE = {
    RED: 0,
    BLUE: 1,
    GREEN: 2,
    YELLOW: 3,
    DARK_RED: 4,
    DARK_BLUE: 5,
    BRONZE: 6,
    DARK_GREEN: 7,
    GOLD: 8,
    CYAN: 9,
    PINK: 10,
    WHITE: 11,
    PURPLE: 12,
    BLACK: 13,
    GRAY: 14,
    CREAM: 15,
    LIME: 16,
    CUSTOM_1: 17,
    CUSTOM_2: 18,
    CUSTOM_3: 19,
    CUSTOM_4: 20,
    CUSTOM_5: 21,
    CUSTOM_6: 22,
    CUSTOM_7: 23,
    CUSTOM_8: 24,
    SUNSET: 25,
    _COUNT: 26
};

export const POWER_TYPE = {
    MAJOR: 0,
    MINOR: 1,
    REGIONAL: 2,
    _COUNT: 3
};

export const NATION_TYPE = {
    SOMERTIN: 0,
    KARGIT: 1,
    TRANSKAL: 2,
    POLASIE: 3,
    ELAM: 4,
    _COUNT: 5
};

export const CURRENCY_TYPE = {
    NONE: 0,
    ZLOT: 1,
    KARGIL: 2,
    KRONE: 3,
    PULA: 4,
    RIAL: 5,
    _COUNT: 6
};

export const FACTION_TYPE = {
    RED: 0,
    BLUE: 1,
    GREEN: 2,
    YELLOW: 3,
    DARK_RED: 4,
    DARK_BLUE: 5,
    BRONZE: 6,
    DARK_GREEN: 7,
    GOLD: 8,
    CYAN: 9,
    PINK: 10,
    WHITE: 11,
    PURPLE: 12,
    BLACK: 13,
    GRAY: 14,
    CREAM: 15,
    LIME: 16,
    SOMERTIN: 17,
    KARGIT: 18,
    TRANSKAL: 19,
    POLASIE: 20,
    ELAM: 21,
    KANYE: 22,
    NYPD: 23,
    _COUNT: 24
};

export const COMMANDER_TYPE = {
    NONE: 0,
    KANYE: 1,
    _COUNT: 2
};

export const BUILDING_TYPE = {
    AIR_CONTROL: 0,
    COMMAND_CENTER: 1,
    FACTORY: 2,
    GROUND_CONTROL: 3,
    OIL_ADVANCED_REFINERY: 4,
    OIL_REFINERY: 5,
    OIL_RIG: 6,
    SEA_CONTROL: 7,
    _COUNT: 8
};

export const ENTITY_TYPE = {
    _INVALID: -1,
    LIGHT_INFANTRY: 0,
    INFANTRY: 1,
    ASSAULT_INFANTRY: 2,
    SNIPERS: 3,
    HEAVY_SNIPER: 4,
    MARINES: 5,
    STORMTROOPERS: 6,
    SPEC_OPS: 7,
    GUARDS: 8,
    PALADIN: 9,
    PANZERHENKER: 10,
    SPARTANS: 11,
    STRIKE_COMMANDO: 12,
    HEAVY_COMMANDO: 13,
    SPIDER_TANK: 14,
    SUICIDE_BOMBER: 15,
    PROFESSIONAL_TERRORIST: 16,
    ANTI_TANK: 17,
    INFANTRY_TRUCK: 18,
    MORTAR_TRUCK: 19,
    ROCKET_TRUCK: 20,
    PULA: 21,
    SUPPLY_TRUCK: 22,
    JAMMER_TRUCK: 23,
    ASEKARA_TANK: 24,
    CRAB_TANK: 25,
    COCKROACH: 26,
    BOLT_TANK: 27,
    FLAK_TANK: 28,
    TANK_HUNTER: 29,
    AMPAC: 30,
    AYIN: 31,
    GORLITZ_TANK: 32,
    KOSCHEI: 33,
    ENTWICKLUNG: 34,
    ENTWICKLUNG_MK2: 35,
    IMPERTERRITUS: 36,
    ROLAND: 37,
    STEALTH_TANK: 38,
    ANNIHILATOR_TANK: 39,
    BERTHA_BATTERY: 40,
    BRIMSTONE_BATTERY: 41,
    WARMACHINE: 42,
    HUNTER_SUPPORT: 43,
    INTREPID: 44,
    U_BOAT: 45,
    LEVIATHAN_BARGE: 46,
    CORVETTE_FIGHTER: 47,
    BATTLESHIP: 48,
    SUPER_BATTLESHIP: 49,
    RAPTOR_FIGHTER: 50,
    VULTURE_DRONE: 51,
    EAGLE_STRIKER: 52,
    BLIMP: 53,
    CONDOR_BOMBER: 54,
    SOLOVEY_BOMBER: 55,
    AKONTIO: 56,
    ZEUS: 57,
    STIHIE: 58,
    ALEPH: 59,
    ALBATROSS_TRANSPORT: 60,
    PELICAN_TRANSPORT: 61,
    STORK_TRANSPORT: 62,
    TURRET: 63,
    BLOCKADE: 64,
    BASTION: 65,
    DEPOT: 66,
    FORTRESS: 67,
    MEME_WTC: 68,
    MEME_BUREAUCRAT: 69,
    _COUNT: 70
};

export const MORALE_TYPE = {
    LOWEST: 0,
    SUPER_LOW: 1,
    VERY_LOW: 2,
    LOW: 3,
    NORMAL: 4,
    HIGH: 5,
    VERY_HIGH: 6,
    SUPER_HIGH: 7,
    ULTRA_HIGH: 8,
    HIGHEST: 9,
    _COUNT: 10
};

export const ACTION_TYPE = {
    MINE_TRIGGER: 0,
    PURCHASE_ENTITY: 1,
    PRODUCE_ENTITY: 2,
    EXTRACT: 3,
    ENTITY_SPAWN: 4,
    EXPLODE_TILE: 5,
    CAPTURE: 6,
    HEAL: 7,
    END_TURN: 8,
    START_TURN: 9,
    MOVE: 10,
    ATTACK: 11,
    CLOAK: 12,
    DEATH: 13,
    UNCLOAK: 14,
    INTERRUPT: 15,
    TO_TRANSPORT: 16,
    FROM_TRANSPORT: 17
};

export const OBJECTIVE_TYPE = {
    DEFEAT: "DEFEAT",
    PROTECT: "PROTECT",
    CAPTURE: "CAPTURE",
    DEFEND: "DEFEND",
    SURVIVE: "SURVIVE",
    TIME_LIMIT: "TIME_LIMIT"
};

export const MOVE_COMMAND = {
    NONE: 0,
    HEAL: 1,
    ATTACK: 2
};

export const COMMAND_TYPE = {
    ATTACK: 0,
    COUNTER: 1
};

export const EFFECT_TYPE = {
    GFX: "GFX",
    SFX: "SFX",
    EXPLOSION: "EXPLOSION"
};

export const COMPONENT_TYPE = {
    PLAY_SPRITE: "PLAY_SPRITE",
    PLAY_SOUND: "PLAY_SOUND",
    DIALOGUE: "DIALOGUE",
    EXPLODE_TILE: "EXPLODE_TILE",
    SPAWN_ENTITY: "SPAWN_ENTITY"
};

export const AUTOTILER_TYPE = {
    PATH: "battalion_path"
};

export const LAYER_TYPE = {
    BUILDING: 0,
    SEA: 1,
    LAND: 2,
    GFX: 3,
    _COUNT: 4
};

export const TILE_ID = {
    NONE: 0,
    GRASS: 1,
    BOREAL: 2,
    ARCTIC: 3,

    ROAD_0: 4,
    ROAD_1: 5,
    ROAD_2: 6,
    ROAD_3: 7,
    ROAD_4: 8,
    ROAD_5: 9,
    ROAD_6: 10,
    ROAD_7: 11,
    ROAD_8: 12,
    ROAD_9: 13,
    ROAD_10: 14,
    ROAD_11: 15,
    ROAD_12: 16,
    ROAD_13: 17,
    ROAD_14: 18,
    ROAD_15: 19,

    VOLANO: 20,

    //21-68: RIVER
    RIVER_0: 21,
    RIVER_10: 31, //Full tile
    RIVER_47: 68,

    SHORE_0: 69,
    SHORE_1: 70,
    SHORE_2: 71,
    SHORE_3: 72,
    SHORE_4: 73,
    SHORE_5: 74,
    SHORE_6: 75,
    SHORE_7: 76,
    SHORE_8: 77,
    SHORE_9: 78,
    SHORE_10: 79,
    SHORE_11: 80,

    ISLAND_1: 81,
    ISLAND_2: 82,
    ISLAND_3: 83,
    ISLAND_4: 84,
    SWIRL_1: 85,
    SWIRL_2: 86,
    SWIRL_3: 87,
    SWIRL_4: 88,
    ROCKS_1: 89,
    ROCKS_2: 90,
    ROCKS_3: 91,
    ROCKS_4: 92,

    OVERLAY_MOVE: 93,
    OVERLAY_MOVE_ATTACK: 94,
    OVERLAY_ATTACK_LIGHT: 95,
    OVERLAY_ATTACK: 96,

    PATH_0: 97,
    PATH_UP: 101,
    PATH_RIGHT: 102,
    PATH_DOWN: 103,
    PATH_LEFT: 104,
    PATH_CENTER: 105,
    PATH_15: 112,

    JAMMER: 113,

    ORE_LEFT: 114,
    ORE_RIGHT: 115,
    ORE_LEFT_USED: 116,
    ORE_RIGHT_USED: 117,
    ORE_LEFT_DEPLETED: 118,
    ORE_RIGHT_DEPLETED: 119,
    
    CANYON_0: 120,
    CANYON_47: 167,

    RAIL_0: 168,
    RAIL_15: 183,

    MINE_LAND: 184,
    MINE_SEA: 185,

    MARKER_WEAK: 186,
    MARKER: 187,
    MARKER_PROTECTED: 188,

    CASH_BOX: 189,

    SHRUB_0: 190,
    SHRUB_4: 194,

    _COUNT: 195
};

export const DIRECTION = {
    NORTH: 0,
    EAST: 1,
    SOUTH: 2,
    WEST: 3,
    _COUNT: 4
};

export const RANGE_TYPE = {
    NONE: 0,
    MELEE: 1,
    RANGE: 2,
    HYBRID: 3
};

export const ATTACK_FLAG = {
    NONE: 0,
    COUNTER: 1 << 0,
    SHRAPNEL: 1 << 1,
    AREA: 1 << 2,
    STREAMBLAST: 1 << 3
};

export const PATH_FLAG = {
    NONE: 0,
    UNREACHABLE: 1 << 0,
    START: 1 << 1
};

export const PATH_INTERCEPT = {
    NONE: 0,
    VALID: 1,
    ILLEGAL: 2,
    MINE: 3
};

export const ATTACK_TYPE = {
    REGULAR: 0,
    STREAMBLAST: 1,
    DISPERSION: 2,
    SUPPLY: 3
};

export const TRANSPORT_TYPE = {
    BARGE: 0,
    PELICAN: 1,
    STORK: 2
};