export const TRAIT_CONFIG = {
    SHRAPNEL_RANGE: 1,
    ABSORBER_RATE: 0.2,
    OVERHEAT_DAMAGE: 0.1,
    HEROIC_THRESHOLD: 1,
    JUDGEMENT_RANGE: 2,
    DISPERSION_RANGE: 1,
    STEER_REDUCTION: 0.1,
    STEER_MAX_REDUCTION: 0.5,
    SCHWERPUNKT_MULTIPLIER: 1.4,
    STEALTH_MULTIPLIER: 2
};